// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHtwThqcN_IWOtGO6ko0q8ML8SmAV7olI',
    appId: '1:297000825350:web:de0bdb2746a2ff2126c987',
    messagingSenderId: '297000825350',
    projectId: 'spelliam-ad3fd',
    authDomain: 'spelliam-ad3fd.firebaseapp.com',
    storageBucket: 'spelliam-ad3fd.firebasestorage.app',
    measurementId: 'G-RNDYC6BTNM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkPTt4XzReJHkGe0Ew8_CM_OggTrokKEQ',
    appId: '1:297000825350:android:8742727f6ae3d13f26c987',
    messagingSenderId: '297000825350',
    projectId: 'spelliam-ad3fd',
    storageBucket: 'spelliam-ad3fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvJZNahOk7ALdp2cym4d-daCKjqPMjbZg',
    appId: '1:297000825350:ios:60fa3fe70abfc04526c987',
    messagingSenderId: '297000825350',
    projectId: 'spelliam-ad3fd',
    storageBucket: 'spelliam-ad3fd.firebasestorage.app',
    iosClientId:
        '297000825350-hd2qe5d6f1nbc4tsb8gp96d2rcuibp72.apps.googleusercontent.com',
    iosBundleId: 'tech.rimotli.alliamApp',
  );
}
